modLoader="javafml" 
loaderVersion="[2,)"
issueTrackerURL="https://github.com/noobanidus/TooFast/issues"
license="https://github.com/noobanidus/TooFast/blob/1.18/LICENSE"
[[mods]] 
    modId="toofast"
    version="0.8.5.8"
    displayName="Too Fast"
    displayURL="https://minecraft.curseforge.com/projects/too-fast"
    authors="Noobanidus"
    description='''
Disables "moved too quickly".
'''
[[mixins]]
config="toofast.mixins.json"
[[dependencies.TooFast]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
[[dependencies.TooFast]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5)"